### PR TITLE
Multilingual support

### PR DESCRIPTION
**Pull request by sutux**
Hi!

I added a multilingual button to the theme that would solve #7 .

It forwards to the page in the correct language. If there is no associated page it forwards to home in the desired language.

If you merge these changes please don't forget to update the image in the README.md.

### CODE REVIEW

**Review by half-duplex — DISMISSED** [review]
Excellent, thank you!

I don't think this needs to break backwards compatibility, but it currently does - trying to build the exampleSite from the main branch with these template changes produces:
```
ERROR 2022/09/25 17:28:17 EXECUTE-AS-TEMPLATE: failed to transform "sass/main.scss" (text/x-scss): template: sass/main.scss:930:17: executing "sass/main.scss" at <index .Site.Data .Site.Language.Lang "homepage" "banner" "image">: error calling index: index of nil pointer
Error: Error building site: failed to render pages: render of "home" failed: "hugo-arcana/layouts/index.html:13:20": execute of template failed: template: index.html:13:20: executing "index.html" at <index .Site.Data .Site.Language.Lang "homepage">: error calling index: index of nil pointer
```

Would you be able to have that fail through to finding the unspecified-locale data if locale-specific data don't exist?

Not a blocker, but on mobile when tapping the language selector in the sidebar the options appear offscreen. I'm not sure what the best way to fix this would be.

Nit: There are also two files without trailing newlines, and one with an extra trailing newline.

**Comment by sutux** [comment]
Thank you for the review.

I implemented the fail through by adding a default to the unspecified-locale data and removed/added the newlines.

I'm not sure about the language options on mobile. I added a `display: none` to the options. Could you please verify if that has fixed it? If not, can you please add a picture here. This would help me a lot.

**Comment by ainola** [comment]
Thanks for your great work on this, @sutux :)

**Comment by half-duplex** [comment]
Sorry for the delay. Thanks for making those changes, and thank you again for the PR.

> I'm not sure about the language options on mobile. I added a `display: none` to the options. Could you please verify if that has fixed it?

On mobile, when the `:globe_with_meridians: en` in the menu is tapped, the language options appear below, but that part is off-screen until the user scrolls down further. I think ideally the scroll position would be bumped down to the bottom of the language options? But I don't love how that would move everything else on the screen, so... Not sure. Either way, everything else is great.

**Comment by mathieugouin** [comment]
Hello @sutux and @half-duplex.  I found something strange related to this change:
File: `layouts/partials/head/head.html`  import `head/languages.html`.  In this file, there are `ul`, `li`, ... I'm not sure this is allowed in the `<head>` section of an html document?

```html
<html lang="{{ .Language }}">
    <head>
        {{- partial "head/head.html" . -}}
...
```

Thanks!

**Comment by half-duplex** [comment]
@mathieugouin Fixed in fe1f4ce, thank you!

**Comment by sutux** [comment]
Hello! I'm glad to hear that everything is fine now. It has been quite a long time since I worked with this repository, so it would take a bit of time to check the issue with mobile settings. If that's no longer a problem, I'll remove it from my to-do list. :)

**Comment by mathieugouin** [comment]
Glad to help !

@sutux It is possible to have a mobile version of any web page on your computer using Chrome Dev Tools.

**Pull request merged**
