### PR TITLE
SEO Improvements: Add metaimage and x/twitter card

### PR DESCRIPTION
**Pull request by alichampi**
Hi again, we're using your theme in our new website https://alichampi.com/ and I would like to contribute some possible improvements that I had to make for it upstream to the theme, if you see them fit. This first one is adding a metaimage (only reflected on the example site, but good for reference) and twitter cards.

Source: https://gohugo.io/templates/embedded/#twitter-cards

Other change that I could contribute is managing robots.txt and sitemap.xml with a new param, if it's interesting tell me and I will make it in another pull request. ~Also I'm working on some fixes for the header but it's still not finished, not even on my site.~

Also, feel free to take a peek at the source of my site and any other change you would like to implement, just ask me and I will do it.

### CODE REVIEW

**Comment by alichampi** [comment]
~Marking it as draft temporary as I'm having some problems with it.~

**Comment by alichampi** [comment]
I finally managed to make it work with all social media, Whatsapp was especially problematic. It's ready to merge.

**Comment by half-duplex** [comment]
Thank you!
Did one functional change - the path to the image should be relative so the site can be deployed to a folder instead of just the webroot.

**Comment by half-duplex** [comment]
>Other change that I could contribute is managing robots.txt and sitemap.xml

Generally, I would welcome anything that can be done cleanly, in a generalized or standard manner, and is likely to be useful to other users.

**Pull request merged**
